# Generated by Django 4.1.4 on 2023-01-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='balance',
            new_name='bonus',
        ),
        migrations.AddField(
            model_name='customuser',
            name='money',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=7),
        ),
    ]
