# Generated by Django 4.1.4 on 2023-01-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_balance_customuser_bonus_customuser_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
