# Generated by Django 4.1.4 on 2022-12-28 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type_name', models.CharField(choices=[('card', 'Cartão')], max_length=30, verbose_name='Método de pagamento')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação ')),
                ('id_stripe', models.CharField(max_length=300, verbose_name='id stripe')),
                ('number', models.IntegerField(verbose_name='Número do cartão')),
                ('exp_date', models.DateField(verbose_name='Data de Expiração')),
                ('cvc', models.IntegerField(verbose_name='CVC')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cartão',
                'verbose_name_plural': 'Cartões',
                'db_table': 'card_payment',
            },
        ),
    ]
