# Generated by Django 4.1.4 on 2023-01-01 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saved', models.DateField(auto_now_add=True, verbose_name='Data do pagamento')),
                ('payment_intent_id', models.CharField(max_length=255, verbose_name='Id payment intent stripe')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor da compra')),
                ('payment_method_id', models.CharField(max_length=255, verbose_name='Id do metódo de pagamento')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment', related_query_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
