# Generated by Django 4.1.4 on 2022-12-21 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingool', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ballscards',
            table='balls_cards',
        ),
    ]
