# Generated by Django 4.1.4 on 2022-12-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingool', '0002_alter_ballscards_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='initials',
            field=models.CharField(choices=[('l1', 'Linha 1'), ('l3', 'Linha 2'), ('b1', 'Bingo'), ('b2', 'Bingo2'), ('b3', 'Bingo3'), ('ac', 'Acummulado')], max_length=50, verbose_name='Iniciais'),
        ),
    ]
