# Generated by Django 4.1.4 on 2023-01-03 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bingool', '0004_alter_card_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação ')),
                ('running', models.BooleanField(default=False, verbose_name='Sorteio altomático')),
            ],
            options={
                'verbose_name': 'Bot',
                'db_table': 'bot',
            },
        ),
        migrations.AddField(
            model_name='bingo',
            name='standby',
            field=models.BooleanField(default=False, verbose_name='Bingo em espera'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Bola'),
        ),
        migrations.AlterField(
            model_name='card',
            name='balls',
            field=models.ManyToManyField(through='bingool.BallsCards', to='bingool.ball', verbose_name='Bolas'),
        ),
        migrations.AlterField(
            model_name='card',
            name='state',
            field=models.CharField(choices=[('new', 'Nova'), ('inlive', 'Em jogo'), ('finalized', 'Fora de jogo')], default='new', max_length=10, verbose_name='Estado da cartela'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bingool.card'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
