# Generated by Django 4.1.4 on 2023-01-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingool', '0007_alter_match_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingo',
            name='ball_drawn',
            field=models.IntegerField(null=True, verbose_name='Bola sorteada'),
        ),
    ]
