# Generated by Django 4.1.4 on 2023-01-05 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bingool', '0009_card_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bingool.match'),
        ),
    ]
