# Generated by Django 4.1.4 on 2023-01-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingool', '0010_alter_award_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ball',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='pk'),
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='pk'),
        ),
    ]
