# Generated by Django 4.1.4 on 2023-01-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingool', '0012_alter_ball_id_alter_card_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ballscards',
            options={'ordering': None},
        ),
    ]
