# Generated by Django 4.1.4 on 2023-01-17 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bingool', '0014_alter_award_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='award', related_query_name='awards', to='bingool.match'),
        ),
    ]
