# Generated by Django 4.1.4 on 2023-01-19 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bingool', '0015_alter_award_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingo',
            name='color',
            field=models.CharField(choices=[('color1', 'color1'), ('color2', 'color2'), ('color3', 'color3'), ('color4', 'color4'), ('color5', 'color5'), ('color6', 'color6'), ('color7', 'color7'), ('color8', 'color8'), ('color9', 'color9')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='award', to='bingool.match'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='bingool.award'),
        ),
    ]
