# Generated by Django 4.1.4 on 2023-01-19 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bingool', '0016_bingo_color_alter_award_match_alter_winner_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ball',
            name='bingo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ball', to='bingool.bingo'),
        ),
    ]
