# Generated by Django 4.1.4 on 2023-01-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingool', '0017_alter_ball_bingo'),
    ]

    operations = [
    ]
