# Generated by Django 4.1.4 on 2023-01-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingool', '0018_auto_20230119_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date_to_start',
            field=models.DateField(help_text='Horario não deve ser no passado, escolha um tempo com 10 minutos depois da ultima partida marcada', verbose_name='Data a ser iniciada'),
        ),
    ]
