# Generated by Django 4.1.4 on 2023-01-29 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bingool', '0019_alter_match_date_to_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallsLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação ')),
                ('ball', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bingool.ball')),
            ],
            options={
                'db_table': 'balls_line',
                'ordering': None,
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação ')),
                ('name', models.CharField(max_length=2, verbose_name='Nome')),
                ('balls', models.ManyToManyField(through='bingool.BallsLine', to='bingool.ball', verbose_name='Bolas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='card',
            name='balls',
        ),
        migrations.DeleteModel(
            name='BallsCards',
        ),
        migrations.AddField(
            model_name='line',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line', to='bingool.card'),
        ),
        migrations.AddField(
            model_name='ballsline',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bingool.line'),
        ),
    ]
