# Generated by Django 4.1.4 on 2023-02-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingool', '0021_card_implemented_lines'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'verbose_name': 'Bola', 'verbose_name_plural': 'Bolas'},
        ),
        migrations.AlterModelTable(
            name='line',
            table='line',
        ),
    ]
